services:
  app-java:
    build:
      context: ./app-java
      dockerfile: Dockerfile
    container_name: java_app
    env_file:
      - .env
    depends_on:
      - mysql
    ports:
      - "8080:8080"
  
  app-go:
    build:
      context: ./app-go
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8081:8080"
    depends_on:
      - mysql
  
  app-php-fpm:
    build: ./app-php
    expose:
      - "9000"  # Expose PHP-FPM to Nginx
    env_file:
      - .env
    depends_on:
      - mysql
  
  app-php:
    image: nginx:latest
    volumes:
      - ./app-php/nginx.conf:/etc/nginx/conf.d/default.conf
      # - ./app-php/html:/var/www/html
    ports:
      - "8082:8080"
    depends_on:
      - app-php-fpm

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - app-java
      - app-go
      - app-php
  
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
